version: 2.1
jobs:
  milan:
    docker:
     - image: cypress/browsers:chrome69
    steps:
     - add_ssh_keys:
        fingerprints:
           - "42:1c:5b:f8:dc:f8:d0:a9:0a:7d:7e:bd:ca:1a:37:7c"
     - run:
        name: Clone GitHub repository
        command: git clone git@github.com:uxi187/Demo.git
     - run:
        name: Ls
        command: dir
     - persist_to_workspace:
         root: ~/project
         paths:
           - Demo
  run_cypress:
    docker:
     - image: cypress/browsers:chrome69
    parallelism: 1
    steps:
     - attach_workspace:
        at: ~/
     - run:
        name: Directory
        command: dir
     - run:
        name: Ls
        command: dir
     - run:
        name: Npm CI
        command: npm ci
        working_directory: ''
     - run:
        command: npx cypress verify
        working_directory: ''
     - run:
        command: npm run spec_test:suka
        working_directory: ''
workflows:
  build:
    jobs:
      - milan
      - run_cypress:
          requires:
            - milan
     