version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
jobs:
  milan: 
    docker:
     - image: cypress/browsers:chrome69
    steps:
     - persist_to_workspace:
         root: ~/project/Demo
     - checkout
     - run:
        name: Clone GitHub repository
        command: git clone git@github.com:uxi187/Demo.git
     - run:
        name: Ls
        command: dir
workflows:
  build:
    jobs:
      - milan
      - cypress/run:
          executor: cypress/browsers-chrome69
          command: npm run spec_test:suka
          working_directory: ~/project/Demo
            - attach_workspace:
                at: ~/project/Demo
          post-steps:
            - run: node cypress/support/reporter.js
            - store_artifacts:
                path: /root/project/cypress/output
            - store_artifacts:
                path: /root/project/test-results/cucumber-json
            - store_test_results:
                path: /root/project/test-results/cucumber-json
                prefix: test
          requires:
            - milan
     