version: 2
jobs:
  cypress/run:
    docker:
    - image: cypress/browsers:chrome69
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Check if package-lock.json exists
        command: |
          if [ ! -e ./package-lock.json ]; then
            echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
            echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
            echo "and commit 'package-lock.json' to your repo."
            exit 1
          fi
        working_directory: ''
    - run:
        name: Npm CI
        command: npm ci
        working_directory: ''
    - run:
        command: npx cypress verify
        working_directory: ''
    - save_cache:
        key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - run:
        command: npx cypress-tags run -e TAGS='@forgotpass' --env configFile=prod
          --browser chrome
        working_directory: ''
	steps:
    - run:
        command: node cypress/support/reporter.js
		when: always
    - store_artifacts:
        path: /root/project/cypress/output
    - store_artifacts:
        path: /root/project/cypress/test-results/cucumber-json
    - store_test_results:
        path: /root/project/cypress/test-results/cucumber-json
        prefix: test
workflows:
  build:
    jobs:
    - cypress/run
  version: 2