version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
jobs:
  milan: 
    docker:
     - image: cypress/browsers:chrome69
    steps:
     - checkout
     - run:
        name: Clone GitHub repository
        command: git clone git@github.com:uxi187/Demo.git
     - run:
        name: Clone GitHub repository
        command: npm ci && npm run spec_test:suka
        working_directory: ~/Demo
workflows:
  build:
    jobs:
      - milan
      - cypress/run:
          no-workspace: true
          executor: cypress/browsers-chrome69
          command: npm run spec_test:nav
          post-steps:
            - run: node cypress/support/reporter.js
            - store_artifacts:
                path: /root/project/cypress/output
            - store_artifacts:
                path: /root/project/test-results/cucumber-json
            - store_test_results:
                path: /root/project/test-results/cucumber-json
                prefix: test
          requires:
            - milan
     