version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
jobs:
  milan: 
    docker:
     - image: cypress/browsers:chrome69
    steps:
     - add_ssh_keys:
         fingerprints:
            - "62:72:6a:52:5a:a7:35:b7:88:a0:d8:20:23:fe:e5:c1"
     - checkout
     - run:
        name: Clone GitHub repository
        command: git clone git@github.com:uxi187/Demo.git
     - run:
        name: see tree
        command: ls
     - run:
        name: Update npm
        command: 'npm run spec_test:suka'
workflows:
  build:
    jobs:
      - milan
      - cypress/run:
          no-workspace: true
          executor: cypress/browsers-chrome69
          command: npm run spec_test:nav
          post-steps:
            - run: node cypress/support/reporter.js
            - store_artifacts:
                path: /root/project/cypress/output
            - store_artifacts:
                path: /root/project/test-results/cucumber-json
            - store_test_results:
                path: /root/project/test-results/cucumber-json
                prefix: test
          requires:
            - milan
     