version: 2.1
jobs:
  milan:
    docker:
     - image: cypress/browsers:chrome69
    steps:
     - checkout
     - run:
        name: Clone GitHub repository
        command: git clone git@github.com:uxi187/Demo.git
     - run:
        name: Ls
        command: dir
     - persist_to_workspace:
         root: ~/project
         paths:
           - Demo/*
  run_cypress:
    docker:
     - image: cypress/browsers:chrome69
    parallelism: 1
    steps:
     - checkout
     - attach_workspace:
        at: ~/
     - run:
        name: Ls
        command: dir
     - restore_cache:
        keys:
         - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
     - run:
        name: Ls
        command: dir
     - run:
        name: Check if package-lock.json exists
        command: |
          if [ ! -e ./package-lock.json ]; then
            echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
            echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
            echo "and commit 'package-lock.json' to your repo."
            exit 1
          fi
        working_directory: ''
     - run:
        name: Npm CI
        command: npm ci
        working_directory: ''
     - run:
        command: npx cypress verify
        working_directory: ''
     - save_cache:
        key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
     - run:
        command: npm run spec_test:suka
        working_directory: ''
workflows:
  build:
    jobs:
      - milan
      - run_cypress:
          requires:
            - milan
     